name:                pure-framework-chat
version:             0.1.0.0
github:              "gelisam/pure-framework-chat"
license:             PublicDomain
author:              "Samuel Gélineau"
maintainer:          "gelisam@gmail.com"

extra-source-files:
- README.md

dependencies:
- base

executables:
  pure-framework-chat:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
